-- create database taskdb;
-- use taskdb;
-- CREATE table tasks(
-- 	id int primary key auto_increment not null,
--     taskname nvarchar(30),
--     taskdescription nvarchar(80),
--     assignedto nvarchar(30),
--     duedate date,
--     iscompleted tinyint(1)
-- );

-- insert into tasks values(0,'water plants','water all the plants','yosha', 20220912,0);
